Fix style: Space the cards 16px apart, The height of the environment …
masastack/MASA.PM pull request #299
Opened 2023-03-07 08:36 UTC by zyz

…list item is 48px, environment list item hover background color is #F6F8FD

# Description

_1.Space the cards 16px apart
  2.The height of the environment list item is 48px
  3.Environment list item hover background color is #F6F8FD_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2023-03-07 10:34 UTC, doddgu commented
@codding-y PTAL

2023-03-10 03:07 UTC, codding-y requested changes

2023-03-10 03:07 UTC, codding-y commented on src/Web/MASA.PM.Web.Admin/Pages/Home/Overview.razor
> +                        <MTab Value="envClusterId">
If the width is not given, the width will be adaptive and does not conform to the design

2023-03-10 05:54 UTC, zyz commented
style deleted, use the style of css file, css file delete max-width

2023-03-10 06:00 UTC, codding-y approved these changes

2023-03-10 06:00 UTC, merged